<a href="https://colab.research.google.com/github/PanTongLin/PanTongLin.github.io/blob/master/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

## batch to space

In [ ]:
a = torch.Tensor([[[[1], [3]], [[9], [11]]],
          [[[2], [4]], [[10], [12]]],
          [[[5], [7]], [[13], [15]]],
          [[[6], [8]], [[14], [16]]]])
print(a.size())
bs = a.size(0)
hs = a.size(1)
ws = a.size(2)
cs = a.size(3)

In [ ]:
block_s = (2, 2)

In [ ]:
_bs = bs//block_s[1]
_ws = ws*block_s[1]
b = a.reshape((_bs, block_s[1], hs, ws, cs))
b = b.permute(0, 2, 3, 1, 4) #_bs, hs, _ws, block_s[1], cs
b = b.reshape((_bs, hs, _ws, cs))
print(b)

_bs = _bs//block_s[0]
_hs = hs*block_s[0]
b = b.reshape((_bs, block_s[0], hs, _ws, cs))
b = b.permute(0, 2, 1, 3, 4) #_bs, hw, block_s[0], _ws, cs
b = b.reshape((_bs, _hs, _ws, cs))
print(b)

## space to batch

In [ ]:
a = torch.Tensor([[[[1.], [2.], [3.], [4.]],
           [[5.], [6.], [7.], [8.]],
           [[9.], [10.], [11.], [12.]],
           [[13.], [14.], [15.], [16.]]]])
print(a.size())
bs = a.size(0)
hs = a.size(1)
ws = a.size(2)
cs = a.size(3)

In [ ]:
block_s = (2, 2)

In [ ]:
_bs = bs*block_s[0]
_hs = hs//block_s[0]
b = a.reshape((bs, _hs, block_s[0], ws, cs))
b = b.permute(0, 2, 1, 3, 4)
b = b.reshape((_bs, _hs, ws, cs))
print(b)

_ws = ws//block_s[1]
b = b.reshape((_bs, _hs, _ws, block_s[1], cs))
b = b.permute(0, 3, 1, 2, 4)
_bs = _bs*block_s[1]
b = b.reshape((_bs, _hs, _ws, cs))
print(b)

## space to depth

In [ ]:
a = torch.Tensor([[[[1.], [2.], [5.], [6.]],
           [[3.], [4.], [7.], [8.]],
           [[9.], [10.], [13.], [14.]],
           [[11.], [12.], [15.], [16.]]]])
print(a.size())
bs = a.size(0)
hs = a.size(1)
ws = a.size(2)
cs = a.size(3)

torch.Size([1, 4, 4, 1])


In [ ]:
block_s = 2

In [ ]:
_hs = hs//block_s
_ws = ws//block_s
_cs = cs*block_s*block_s
b = a.reshape((bs, _hs, block_s, _ws, block_s, cs))
b = b.permute(0, 1, 3, 2, 4, 5)
b = b.reshape((bs, _hs, _ws, _cs))
print(b)

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.]],

         [[ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])


In [2]:
import tensorflow as tf

In [10]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]],
                 [[3, 3, 3], [4, 4, 4]],
                 [[5, 5, 5], [6, 6, 6]]])
print(tf.strided_slice(t, [1, 0, 0], [2, 1, 3], [1, 1, 1]))  # [[[3, 3, 3]]]
print(tf.strided_slice(t, [1, 0, 0], [2, 1, 1], [1, 1, 1]))  # [[[3, 3, 3]]]

tf.Tensor([[[3 3 3]]], shape=(1, 1, 3), dtype=int32)
tf.Tensor([[[3]]], shape=(1, 1, 1), dtype=int32)


In [22]:
t = [tf.constant([i, i, i, i]) for i in range(4)]
output = tf.constant([0, 0, 0, 0])

output = tf.raw_ops.While(t, output>2, body)

output

tf.Tensor([False False False False], shape=(4,), dtype=bool)


TypeError: ignored